-- Migration 0008 DOWN
DROP TABLE IF EXISTS report_jobs CASCADE;
DROP TABLE IF EXISTS platform_settings CASCADE;
DROP TABLE IF EXISTS wishlists CASCADE;
DROP TABLE IF EXISTS search_logs CASCADE;
DROP TABLE IF EXISTS ip_blocks CASCADE;
DROP TABLE IF EXISTS blacklisted_phones CASCADE;
DROP TABLE IF EXISTS buyer_risk_profiles CASCADE;
DROP TABLE IF EXISTS notification_logs CASCADE;
DROP TABLE IF EXISTS device_tokens CASCADE;
DROP TABLE IF EXISTS notification_templates CASCADE;
DROP TABLE IF EXISTS review_media CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
