package auth

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"math/big"
	"regexp"
	"strings"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/google/uuid"
	"github.com/redis/go-redis/v9"
	"golang.org/x/crypto/bcrypt"

	"github.com/yourusername/ecom-backend/config"
	"github.com/yourusername/ecom-backend/pkg/middleware"
	"github.com/yourusername/ecom-backend/pkg/response"
)

// Handler holds all dependencies for the auth domain.
type Handler struct {
	cfg   *config.Config
	store Store   // interface to DB operations (generated by sqlc + repository)
	redis *redis.Client
}

// NewHandler creates a new auth handler.
func NewHandler(cfg *config.Config, store Store, redis *redis.Client) *Handler {
	return &Handler{cfg: cfg, store: store, redis: redis}
}

// ── Request/Response Types ────────────────────────────────────

type SendOTPRequest struct {
	Phone   string `json:"phone" validate:"required,min=11,max=15"`
	Purpose string `json:"purpose" validate:"required,oneof=LOGIN REGISTER COD_VERIFY WITHDRAWAL_VERIFY PASSWORD_RESET"`
}

type VerifyOTPRequest struct {
	Phone   string `json:"phone" validate:"required"`
	OTP     string `json:"otp" validate:"required,len=6"`
	Purpose string `json:"purpose" validate:"required"`
}

type RegisterRequest struct {
	FullName    string `json:"full_name" validate:"required,min=2,max=255"`
	Email       string `json:"email" validate:"omitempty,email"`
	Password    string `json:"password" validate:"required,min=8,max=72"`
	ReferralCode string `json:"referral_code" validate:"omitempty,len=8"`
}

type LoginEmailRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required"`
}

type TokenResponse struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int64  `json:"expires_in"`
	TokenType   string `json:"token_type"`
	User        UserResponse `json:"user"`
}

type UserResponse struct {
	ID              string `json:"id"`
	FullName        string `json:"full_name"`
	Phone           string `json:"phone,omitempty"`
	Email           string `json:"email,omitempty"`
	Role            string `json:"role"`
	Status          string `json:"status"`
	PhoneVerified   bool   `json:"phone_verified"`
	EmailVerified   bool   `json:"email_verified"`
	ProfilePicture  string `json:"profile_picture_url,omitempty"`
	ReferralCode    string `json:"referral_code"`
}

// ── Handlers ──────────────────────────────────────────────────

// SendOTP handles POST /auth/otp/send
// Sends a 6-digit OTP to the provided BD phone number.
// Rate limited: 5 OTPs per phone per hour.
func (h *Handler) SendOTP(c *fiber.Ctx) error {
	var req SendOTPRequest
	if err := c.BodyParser(&req); err != nil {
		return response.BadRequest(c, "INVALID_BODY", "Invalid request body")
	}

	// Validate BD phone number format
	if !isValidBDPhone(req.Phone) {
		return response.BadRequest(c, "INVALID_PHONE", "Phone must be a valid Bangladeshi number (01XXXXXXXXX)")
	}

	req.Phone = normalizePhone(req.Phone)

	// Store phone for rate limiter middleware
	c.Locals("rate_limit_phone", req.Phone)

	// Check if phone is blacklisted
	blacklisted, err := h.store.IsPhoneBlacklisted(c.Context(), req.Phone)
	if err == nil && blacklisted {
		return response.Forbidden(c, "Your phone number has been restricted. Please contact support.")
	}

	// Check rate limit: 5 OTPs per hour per phone
	countKey := fmt.Sprintf("otp:count:%s", req.Phone)
	count, _ := h.redis.Get(c.Context(), countKey).Int()
	if count >= h.cfg.Fraud.OTPRateLimitPerHour {
		return response.TooManyRequests(c, "OTP limit reached. Please wait before requesting again.")
	}

	// Check if user exists (for REGISTER vs LOGIN)
	userExists, _ := h.store.CheckPhoneExists(c.Context(), req.Phone)
	if req.Purpose == "REGISTER" && userExists {
		return response.Conflict(c, "PHONE_EXISTS", "This phone number is already registered. Please login.")
	}
	if req.Purpose == "LOGIN" && !userExists {
		return response.NotFound(c, "Account with this phone number")
	}

	// Generate 6-digit OTP
	otp, err := generateOTP()
	if err != nil {
		return response.InternalError(c)
	}

	// Hash OTP before storing
	otpHash, err := bcrypt.GenerateFromPassword([]byte(otp), 10)
	if err != nil {
		return response.InternalError(c)
	}

	// Store OTP in DB (expires in 5 minutes)
	expiresAt := time.Now().Add(5 * time.Minute)
	_, err = h.store.CreateOTP(c.Context(), CreateOTPParams{
		Phone:     req.Phone,
		OtpHash:   string(otpHash),
		Purpose:   req.Purpose,
		ExpiresAt: expiresAt,
		IPAddress: c.IP(),
	})
	if err != nil {
		return response.InternalError(c)
	}

	// Increment rate limit counter
	pipe := h.redis.Pipeline()
	pipe.Incr(c.Context(), countKey)
	pipe.Expire(c.Context(), countKey, time.Hour)
	pipe.Exec(c.Context())

	// Send OTP via SMS (async job)
	if err := h.enqueueSendSMS(req.Phone, otp); err != nil {
		// Log but don't fail — SMS gateway might be slow
		// In dev: log OTP to console
		if h.cfg.IsDevelopment() {
			fmt.Printf("DEV MODE — OTP for %s: %s\n", req.Phone, otp)
		}
	}

	return response.OKWithMessage(c, fmt.Sprintf("OTP sent to %s", maskPhone(req.Phone)), fiber.Map{
		"expires_in_seconds": 300,
		"masked_phone":       maskPhone(req.Phone),
	})
}

// VerifyOTP handles POST /auth/otp/verify
// Validates OTP and returns JWT tokens.
func (h *Handler) VerifyOTP(c *fiber.Ctx) error {
	var req VerifyOTPRequest
	if err := c.BodyParser(&req); err != nil {
		return response.BadRequest(c, "INVALID_BODY", "Invalid request body")
	}

	req.Phone = normalizePhone(req.Phone)

	// Get latest valid OTP from DB
	otpRecord, err := h.store.GetLatestValidOTP(c.Context(), GetLatestValidOTPParams{
		Phone:   req.Phone,
		Purpose: req.Purpose,
	})
	if err != nil {
		return response.BadRequest(c, "OTP_INVALID", "Invalid or expired OTP")
	}

	// Check attempt count (max 5 attempts per OTP)
	if otpRecord.AttemptCount >= 5 {
		return response.TooManyRequests(c, "Too many failed attempts. Please request a new OTP.")
	}

	// Increment attempt count
	h.store.IncrementOTPAttempts(c.Context(), otpRecord.ID)

	// Verify OTP hash
	if err := bcrypt.CompareHashAndPassword([]byte(otpRecord.OtpHash), []byte(req.OTP)); err != nil {
		return response.BadRequest(c, "OTP_INVALID", "Invalid OTP. Please try again.")
	}

	// Mark OTP as used
	h.store.MarkOTPUsed(c.Context(), otpRecord.ID)

	// Get or create user
	user, err := h.store.GetUserByPhone(c.Context(), req.Phone)
	if err != nil {
		// New user — create with PENDING_VERIFICATION status
		user, err = h.store.CreateUser(c.Context(), CreateUserParams{
			Phone:         &req.Phone,
			Role:          "CUSTOMER",
			Status:        "ACTIVE",
			PhoneVerified: true,
		})
		if err != nil {
			return response.InternalError(c)
		}
	} else {
		// Existing user — verify phone if not already
		if !user.PhoneVerified {
			h.store.SetUserPhoneVerified(c.Context(), user.ID)
		}
	}

	// Reset login attempts
	h.store.ResetLoginAttempts(c.Context(), user.ID)

	// Generate tokens
	return h.issueTokens(c, user)
}

// RegisterEmail handles POST /auth/register/email
// Creates a new account with email + password.
func (h *Handler) RegisterEmail(c *fiber.Ctx) error {
	var req RegisterRequest
	if err := c.BodyParser(&req); err != nil {
		return response.BadRequest(c, "INVALID_BODY", "Invalid request body")
	}

	// Check email exists
	if req.Email != "" {
		exists, _ := h.store.CheckEmailExists(c.Context(), req.Email)
		if exists {
			return response.Conflict(c, "EMAIL_EXISTS", "An account with this email already exists")
		}
	}

	// Hash password
	passwordHash, err := bcrypt.GenerateFromPassword([]byte(req.Password), 12)
	if err != nil {
		return response.InternalError(c)
	}

	// Handle referral
	var referredByID *uuid.UUID
	if req.ReferralCode != "" {
		referrer, err := h.store.GetUserByReferralCode(c.Context(), req.ReferralCode)
		if err == nil {
			id := referrer.ID
			referredByID = &id
		}
	}

	// Generate unique referral code for new user
	referralCode := generateReferralCode()

	// Create user
	email := req.Email
	user, err := h.store.CreateUser(c.Context(), CreateUserParams{
		Email:         &email,
		PasswordHash:  string(passwordHash),
		FullName:      req.FullName,
		Role:          "CUSTOMER",
		Status:        "ACTIVE",
		ReferralCode:  &referralCode,
		ReferredByID:  referredByID,
	})
	if err != nil {
		return response.InternalError(c)
	}

	// TODO: Send verification email (async job)

	return h.issueTokens(c, user)
}

// LoginEmail handles POST /auth/login/email
func (h *Handler) LoginEmail(c *fiber.Ctx) error {
	var req LoginEmailRequest
	if err := c.BodyParser(&req); err != nil {
		return response.BadRequest(c, "INVALID_BODY", "Invalid request body")
	}

	// Get user (no enumeration — same error for wrong email or password)
	user, err := h.store.GetUserByEmail(c.Context(), req.Email)
	if err != nil || user.PasswordHash == nil {
		return response.Unauthorized(c, "Invalid email or password")
	}

	// Check account lock
	if user.LockedUntil != nil && time.Now().Before(*user.LockedUntil) {
		remaining := time.Until(*user.LockedUntil).Round(time.Minute)
		return response.Unauthorized(c, fmt.Sprintf("Account temporarily locked. Try again in %v.", remaining))
	}

	// Check account status
	if user.Status == "BLOCKED" {
		return response.Forbidden(c, "Your account has been blocked. Please contact support.")
	}

	// Verify password
	if err := bcrypt.CompareHashAndPassword([]byte(*user.PasswordHash), []byte(req.Password)); err != nil {
		// Increment failed attempts
		result, _ := h.store.IncrementLoginAttempts(c.Context(), user.ID)
		if result.LoginAttemptCount >= 10 {
			return response.Unauthorized(c, "Too many failed attempts. Account locked for 30 minutes.")
		}
		return response.Unauthorized(c, "Invalid email or password")
	}

	// Reset login attempts and update last_login
	h.store.ResetLoginAttempts(c.Context(), user.ID)

	return h.issueTokens(c, user)
}

// Refresh handles POST /auth/refresh
// Uses the HTTP-only cookie refresh token to issue new access + refresh tokens.
func (h *Handler) Refresh(c *fiber.Ctx) error {
	// Get refresh token from HTTP-only cookie
	refreshToken := c.Cookies("refresh_token")
	if refreshToken == "" {
		return response.Unauthorized(c, "Refresh token not found")
	}

	// Hash the token and find session
	tokenHash := hashToken(refreshToken)
	session, err := h.store.GetSessionByTokenHash(c.Context(), tokenHash)
	if err != nil {
		return response.Unauthorized(c, "Session not found or expired")
	}

	// Get user
	user, err := h.store.GetUserByID(c.Context(), session.UserID)
	if err != nil {
		return response.Unauthorized(c, "User not found")
	}

	// Rotate refresh token (invalidate old, issue new)
	newRefreshToken := generateSecureToken()
	newTokenHash := hashToken(newRefreshToken)
	newExpiry := time.Now().Add(h.cfg.JWT.RefreshExpiry)

	if err := h.store.UpdateSessionToken(c.Context(), UpdateSessionParams{
		ID:               session.ID,
		RefreshTokenHash: newTokenHash,
		ExpiresAt:        newExpiry,
	}); err != nil {
		return response.InternalError(c)
	}

	// Generate new access token
	accessToken, err := middleware.GenerateAccessToken(
		user.ID.String(), user.Role, session.ID.String(),
		h.cfg.JWT.AccessSecret, h.cfg.JWT.AccessExpiry,
	)
	if err != nil {
		return response.InternalError(c)
	}

	// Set new HTTP-only cookie
	setRefreshTokenCookie(c, newRefreshToken, newExpiry)

	return response.OK(c, fiber.Map{
		"access_token": accessToken,
		"expires_in":   int64(h.cfg.JWT.AccessExpiry.Seconds()),
		"token_type":   "Bearer",
	})
}

// Logout handles POST /auth/logout
func (h *Handler) Logout(c *fiber.Ctx) error {
	// Get refresh token from cookie
	refreshToken := c.Cookies("refresh_token")
	if refreshToken != "" {
		tokenHash := hashToken(refreshToken)
		session, err := h.store.GetSessionByTokenHash(c.Context(), tokenHash)
		if err == nil {
			// Revoke specific session
			h.store.RevokeSession(c.Context(), session.ID)
		}
	}

	// Blacklist current access token in Redis
	authHeader := c.Get("Authorization")
	if strings.HasPrefix(authHeader, "Bearer ") {
		token := authHeader[7:]
		blacklistKey := fmt.Sprintf("blacklist:token:%s", token[:min(32, len(token))])
		h.redis.Set(c.Context(), blacklistKey, 1, h.cfg.JWT.AccessExpiry)
	}

	// Clear refresh token cookie
	c.Cookie(&fiber.Cookie{
		Name:     "refresh_token",
		Value:    "",
		Expires:  time.Unix(0, 0),
		HTTPOnly: true,
		Secure:   h.cfg.IsProduction(),
		SameSite: "Strict",
	})

	return response.OKWithMessage(c, "Logged out successfully", nil)
}

// GetMe handles GET /auth/me
func (h *Handler) GetMe(c *fiber.Ctx) error {
	userID, _ := uuid.Parse(middleware.GetUserID(c))
	user, err := h.store.GetUserByID(c.Context(), userID)
	if err != nil {
		return response.NotFound(c, "User")
	}

	return response.OK(c, mapUserToResponse(user))
}

// ── Helper Functions ──────────────────────────────────────────

// issueTokens creates a session, generates JWT tokens, and sets cookies.
func (h *Handler) issueTokens(c *fiber.Ctx, user interface{ GetID() uuid.UUID; GetRole() string }) error {
	sessionID := uuid.New()

	// Generate tokens
	accessToken, err := middleware.GenerateAccessToken(
		user.GetID().String(), user.GetRole(), sessionID.String(),
		h.cfg.JWT.AccessSecret, h.cfg.JWT.AccessExpiry,
	)
	if err != nil {
		return response.InternalError(c)
	}

	refreshToken := generateSecureToken()
	tokenHash := hashToken(refreshToken)
	refreshExpiry := time.Now().Add(h.cfg.JWT.RefreshExpiry)

	// Create session in DB
	h.store.CreateSession(context.Background(), CreateSessionParams{
		UserID:           user.GetID(),
		ID:               sessionID,
		RefreshTokenHash: tokenHash,
		IPAddress:        c.IP(),
		UserAgent:        c.Get("User-Agent"),
		ExpiresAt:        refreshExpiry,
	})

	// Set HTTP-only cookie for refresh token
	setRefreshTokenCookie(c, refreshToken, refreshExpiry)

	return response.OK(c, TokenResponse{
		AccessToken: accessToken,
		ExpiresIn:   int64(h.cfg.JWT.AccessExpiry.Seconds()),
		TokenType:   "Bearer",
	})
}

func setRefreshTokenCookie(c *fiber.Ctx, token string, expiry time.Time) {
	c.Cookie(&fiber.Cookie{
		Name:     "refresh_token",
		Value:    token,
		Expires:  expiry,
		HTTPOnly: true,
		Secure:   true,
		SameSite: "Strict",
		Path:     "/api/v1/auth/refresh",
	})
}

func generateOTP() (string, error) {
	max := big.NewInt(1000000)
	n, err := rand.Int(rand.Reader, max)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("%06d", n.Int64()), nil
}

func generateSecureToken() string {
	b := make([]byte, 32)
	rand.Read(b)
	return hex.EncodeToString(b)
}

func generateReferralCode() string {
	b := make([]byte, 4)
	rand.Read(b)
	return strings.ToUpper(hex.EncodeToString(b))
}

func hashToken(token string) string {
	// Simple SHA-256 hash for storage
	// In production use crypto/sha256
	return fmt.Sprintf("%x", token)
}

func isValidBDPhone(phone string) bool {
	re := regexp.MustCompile(`^(?:\+88)?01[3-9]\d{8}$`)
	return re.MatchString(phone)
}

func normalizePhone(phone string) string {
	phone = strings.TrimPrefix(phone, "+88")
	phone = strings.TrimPrefix(phone, "88")
	return phone
}

func maskPhone(phone string) string {
	if len(phone) < 7 {
		return phone
	}
	return phone[:3] + "****" + phone[len(phone)-3:]
}

func mapUserToResponse(user interface{}) *UserResponse {
	// This would map the sqlc-generated User struct to our response type
	// Implementation filled after sqlc generates the types
	return &UserResponse{}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// enqueueSendSMS enqueues an SMS job via asynq
func (h *Handler) enqueueSendSMS(phone, otp string) error {
	// TODO: implement after asynq worker setup
	return nil
}
